
export const  AppConstants = {
    CONTACT_API_URL : "/contact",
    LOGIN_API_URL : "/user",
    ACCOUNT_API_URL : "/account",
    ACCOUNT_SEND_RESETPASSWORD_API_URL : "/account_send_resetpassword",
    GROUPS_API_URL : "/api/groups",
    GROUP_MEMBERS_API_URL : "/api/group_members",
    GROUP_ENTITIES_API_URL : "/api/group_entities",
    GROUP_LOCATIONS_API_URL : "/api/group_locations",
    GROUP_BY_ID_API_URL : "/api/group_by_id",
    NOTICES_API_URL : "/notices",
    USERS_API_URL : "/api/users",
    USERS_RESET_PASSWORD_API_URL : "/api/users_reset_password",
    SYSTEM_TITLE_URL : "/system_title",
    SYSTEM_SUBTITLE_URL : "/system_subtitle",
    TAGS_API_URL : "/api/tags",
    SMTPTEST_API_URL : "/api/smtp_test",
    LOCATION_TAGS_API_URL : "/api/tags_location",
    MONITORED_LOCATIONS_API_URL : "/api/monitored_locations",
    EMAILUSERS_API_URL : "/api/emailusers",
    SMTPSETTINGS_API_URL : "/api/smtpsettings",
    LOCATION_DEVICES_API_URL : "/api/devices_location",
    LOCATION_REMOVEGROUP_API_URL : "/api/location_removegroup",
    LOCATION_ANTENNAS_API_URL : "/api/location_antennas",
    TAGS_UNASSIGNED_API_URL : "/api/tags_unassigned",
    DEVICEMODELS_API_URL : "/api/devicemodels",
    RFIDDEVICES_API_URL : "/api/rfiddevices",
    RFIDDEVICES_STATUS_API_URL : "/api/rfiddevices_status",
    RFIDDEVICES_SETGPO_API_URL : "/api/rfiddevices_setgpo",
    RFIDDEVICES_DRIVERS_API_URL : "/api/devicemodels_drivers",
    PARAMETERS_API_URL : "/api/parameters",
    PARAMETERBYNAME_API_URL : "/api/parameterByName",
    LICENSE_API_URL : "/api/licenses",
    LOCATIONS_API_URL : "/api/locations",
    LOCATION_TREE_API_URL : "/api/location_tree",
    LOCATIONPROPS_API_URL : "/api/locationprops",
    LOCATIONS_CHILDREN_API_URL : "/api/childrenLocations",
    RFIDOBJECT_API_URL : "/api/rfidobjects",
    RFIDENTITY_API_URL : "/api/rfidentities",
    RFIDENTITY_REMOVEGROUP_API_URL : "/api/rfidentity_removegroup",
    REPORTS_API_URL : "/api/reports",
    REPORTS_PDF_API_URL : "/api/reports_pdf",
    REPORTS_CSV_API_URL : "/api/reports_csv",
    SCHEDULES_API_URL : "/api/schedules",
    SCHEDULES_BYTYPE_API_URL : "/api/schedules_bytype",
    CHARTS_API_URL : "/api/charts",
    RFIDENTITY_API_BYCLASS_URL : "/api/getentitiesByClass",
    SCHEDULES_API_PERMISSIONS_URL : "/api/schedules_permissions",
    ACCESSHISTORY_API_URL : "/api/rfidentity_accesshistory",
    LOCATION_TYPES: "LocationType",
    DEVICE_TYPES: "DeviceType",
    version: 'v4.202303011828',
}
